  
{{- range untilStep 1 (int .Values.numApplications) 1 }}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: test-app-{{ . }}
  namespace: argocd
spec:
  destination:
    namespace: test-app-{{ . }}
    server: https://kubernetes.default.svc
  project: loadtest
  source:
    path: test-app-{{ . }}
    repoURL: https://github.com/jannfis/test-multi-app
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
    syncOptions:
    - CreateNamespace=true
{{- end }}
